project:
  type: website
  output-dir: docs

website:
  title: "Watzek User Survey, 2024"
  sidebar:
    style: "docked"
    collapse-level: 1
    logo: _images/owlblack.png
    search: true   
    contents:
      - href: index.qmd
      - href: userSurvey.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true