project:
  type: website
  output-dir: docs

website:
  title: "Watzek User Survey, 2024"
  sidebar:
    style: "docked"
    collapse-level: 1
    logo: image/owl.png
    search: true   
    contents:
      - href: index.qmd
      - href: demographics.qmd
      - href: frequency.qmd
      - href: needs.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true